{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rtmpgate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rtmpgate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.adminToken }}
  admin-token: {{ .Values.secret.adminToken | quote }}
  {{- end }}
  {{- if ne .Values.config.storage "memory" }}
  redis-url: {{ .Values.secret.redisUrl | quote }}
  {{- end }}
{{- end }}
